select *
from DEPT
where DEPTNAME LIKE '%SERVICE%' -- or DEPTNAME LIKE '%SERVICE' or DEPTNAME LIKE 'SERVICE%'
order by DEPTNO ASC

select *
from DEPT
where not DEPTNAME LIKE '%SERVICE%' -- or DEPTNAME LIKE '%SERVICE' or DEPTNAME LIKE 'SERVICE%'
order by DEPTNO ASC